In [18]:
from nltk.corpus import names
import random
from nltk.classify import apply_features
%matplotlib inline
import pandas as pd
import plotly as py
import plotly.graph_objs as go 
from plotly.offline import init_notebook_mode, plot, iplot
import matplotlib.pyplot as plt
init_notebook_mode(connected=True)
import nltk, re, pprint
from nltk import word_tokenize
import string
import re
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.ensemble import RandomForestClassifier

In [5]:
names = ([(name, 'male') for name in names.words('male.txt')] + [(name, 'female') for name in names.words('female.txt')])

In [6]:
name_df = pd.DataFrame(names)
name_df.columns = ['name', 'gender']

In [7]:
name_df['last_letter'] = name_df['name'].apply(lambda x: x[-1])
name_df['first_letter'] = name_df['name'].apply(lambda x: x[0])
name_df['len_name'] = name_df['name'].apply(lambda x: len(x))
name_df['a_count'] = name_df['name'].apply(lambda x: len(re.findall('a',x)))
name_df['i_count'] = name_df['name'].apply(lambda x: len(re.findall('i',x)))
name_df['o_count'] = name_df['name'].apply(lambda x: len(re.findall('o',x)))
name_df['o_count'] = name_df['name'].apply(lambda x: len(re.findall('y',x)))
name_df = pd.get_dummies(name_df, columns=['last_letter','first_letter'])

In [8]:
name_df.head()

name gender  len_name  a_count  i_count  o_count  last_letter_   \
0  Aamir   male         5        1        1        0              0   
1  Aaron   male         5        1        0        0              0   
2  Abbey   male         5        0        0        1              0   
3  Abbie   male         5        0        1        0              0   
4  Abbot   male         5        0        0        0              0   

   last_letter_a  last_letter_b  last_letter_c  ...  first_letter_Q  \
0              0              0              0  ...               0   
1              0              0              0  ...               0   
2              0              0              0  ...               0   
3              0              0              0  ...               0   
4              0              0              0  ...               0   

   first_letter_R  first_letter_S  first_letter_T  first_letter_U  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   first_letter_V  first_letter_W  first_letter_X  first_letter_Y  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   first_letter_Z  
0               0  
1               0  
2               0  
3               0  
4               0  

[5 rows x 58 columns]

In [9]:
def logistic_classifier(df):
    
    X = df.drop(labels=['gender','name'],
                axis=1)
        
    y = df['gender']
    lr = LogisticRegression(penalty='l2',
                            dual=False,
                            max_iter=1000,
                            tol=.0001,
                            C=1)
    X_train, X_test, y_train, y_test = train_test_split(X,
                                                        y,
                                                        test_size=.3)

    lr.fit(X_train,y_train)
    y_pred = lr.predict(X_test)
    print('Test Accuracy',lr.score(X_test, y_test))
    print('Train Accuracy',lr.score(X_train, y_train))
    print('Confusion Matrix')
    print(confusion_matrix(y_test, y_pred))

In [10]:
logistic_classifier(name_df)

Test Accuracy 0.7885906040268457
Train Accuracy 0.789568345323741
Confusion Matrix
[[1305  228]
 [ 276  575]]


In [11]:
def m_naive_bayes_classifier(df):
    
    X = df.drop(labels=['gender','name'],
                axis=1)
        
    y = df['gender']
    nb = MultinomialNB()
    X_train, X_test, y_train, y_test = train_test_split(X,
                                                        y,
                                                        test_size=.3)

    nb.fit(X_train,y_train)
    y_pred = nb.predict(X_test)
    print('Test Accuracy',nb.score(X_test, y_test))
    print('Train Accuracy',nb.score(X_train, y_train))
    print('Confusion Matrix')
    print(confusion_matrix(y_test, y_pred))

In [12]:
naive_bayes_classifier(name_df)

Test Accuracy 0.7739093959731543
Train Accuracy 0.7773381294964029
Confusion Matrix
[[1264  264]
 [ 275  581]]


In [28]:
def random_forest_classifier(df):
    
    X = df.drop(labels=['gender','name'],
                axis=1)
        
    y = df['gender']
    rf=RandomForestClassifier(n_estimators=20,
                              min_samples_split=10)
    X_train, X_test, y_train, y_test = train_test_split(X,
                                                        y,
                                                        test_size=.3)

    rf.fit(X_train,y_train)
    y_pred = rf.predict(X_test)
    print('Test Accuracy',rf.score(X_test, y_test))
    print('Train Accuracy',rf.score(X_train, y_train))
    print('Confusion Matrix')
    print(confusion_matrix(y_test, y_pred))

In [29]:
random_forest_classifier(name_df)

Test Accuracy 0.7785234899328859
Train Accuracy 0.8597122302158273
Confusion Matrix
[[1222  236]
 [ 292  634]]
